version: "3.9"
services:
  web:
    build: .
    container_name: react-vite-web
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    stdin_open: true
    tty: true
